apiVersion: v2
name: external-dns
description: A Helm chart for deployment external-dns on Kubernetes
type: application
version: 1.19.0
dependencies:
  - name: external-dns
    version: 1.19.0
    repository: https://kubernetes-sigs.github.io/external-dns/
