chaos-mesh:
  dashboard:
    securityMode: false
    networkPolicy:
      enabled: true
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        memory: 128Mi

  controllerManager:
    networkPolicy:
      enabled: true
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        memory: 128Mi

  chaosDaemon:
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        memory: 128Mi
