apiVersion: v2
name: sftpgo
description: A Helm chart for deployment sftpgo on Kubernetes
type: application
version: 0.41.0
dependencies:
  - name: sftpgo
    version: 0.41.0
    repository: oci://ghcr.io/sftpgo/helm-charts
