apiVersion: v2
name: monitoring
description: A standard deployment of the Prometheus stack.
type: application
version: 71.0.0
dependencies:
  - name: kube-prometheus-stack
    repository: https://prometheus-community.github.io/helm-charts
    version: 71.2.0
