{{- if and (.Values.metrics.serviceMonitor.enabled) (.Capabilities.APIVersions.Has "monitoring.coreos.com/v1") }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "guestbook.fullname" . }}-redis
  labels:
    {{- include "guestbook.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "guestbook.selectorLabels" . | nindent 6 }}
  endpoints:
    - port: metrics
      interval: 30s
      path: /metrics
{{- end }}
