apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cnpg-cluster-app
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: SecretStore
    name: cnpg-secret-store
  data:
    - secretKey: HOST
      remoteRef:
        key: cnpg-cluster-app
        property: host
  target:
    name: cnpg-cluster-app
    creationPolicy: Owner
