apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cnpg-cluster-app
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: SecretStore
    name: cnpg-secret-store
  target:
    name: cnpg-cluster-app
    creationPolicy: Owner
    template:
      data:
        secret.json: |
          {
            "host": "{{ .host }}",
            "port": {{ .port }},
            "database": "{{ .dbname }}",
            "user": "{{ .username }}",
            "password": "{{ .password }}",
            "ssl": false
          }
  dataFrom:
    - extract:
        key: cnpg-cluster-app
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
