apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cnpg-cluster-app
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: SecretStore
    name: cnpg-secret-store
  target:
    name: cnpg-cluster-app
    creationPolicy: Owner
    template:
      data:
        secret.json: |
          {
            "host": "{{ .host }}",
            "port": {{ .port }},
            "database": "{{ .dbname }}",
            "user": "{{ .username }}",
            "password": "{{ .password }}",
            "ssl": false
          }
  data:
    - secretKey: host
      remoteRef:
        key: cnpg-cluster-app
        property: host
    - secretKey: port
      remoteRef:
        key: cnpg-cluster-app
        property: port
    - secretKey: dbname
      remoteRef:
        key: cnpg-cluster-app
        property: dbname
    - secretKey: username
      remoteRef:
        key: cnpg-cluster-app
        property: username
    - secretKey: password
      remoteRef:
        key: cnpg-cluster-app
        property: password
