apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: n8n-db-credentials
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: gitlab-cluster-store
  target:
    name: n8n-db-credentials
  dataFrom:
    - extract:
        key: n8n-db-credentials
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
