apiVersion: v2
name: my-n8n
description: A Helm chart for deployment n8n on Kubernetes
type: application
version: 1.1.0
dependencies:
  - name: my-n8n
    version: 1.1.0
    repository: oci://8gears.container-registry.com/library/n8n
