apiVersion: v2
name: renovate
description: A Helm chart for deployment renovate on Kubernetes
type: application
version: 11.4.0
dependencies:
  - name: renovate
    version: 45.87.5
    repository: https://docs.renovatebot.com/helm-charts
