apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: orchestra-secrets-source
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: gitlab-cluster-store
    kind: ClusterSecretStore
  target:
    name: ou
  data:
    - secretKey: GITHUB_SECRET_ID
      remoteRef:
        key: GITHUB_SECRET_ID
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
