apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
metadata:
  name: cnpg-cluster-app-push
  namespace: cnpg-cluster
spec:
  refreshInterval: 1h
  secretStoreRefs:
    - name: kubernetes-secret-store
      kind: SecretStore
  selector:
    secret:
      name: cnpg-cluster-app
  data:
    - match:
        secretKey: "*"
        remoteRef:
          remoteKey: cnpg-cluster-app
  target:
    name: cnpg-cluster-app
    namespace: n8n
