apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cnpg-cluster-app
  namespace: n8n
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: SecretStore
    name: cnpg-secret-store
  target:
    name: cnpg-cluster-app
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: cnpg-cluster-app
