apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: cnpg-secret-store
  namespace: n8n
spec:
  provider:
    kubernetes:
      remoteNamespace: cnpg-cluster
      auth:
        serviceAccount:
          name: external-secrets
