apiVersion: v1
kind: ServiceAccount
metadata:
  name: external-secrets
  namespace: cnpg-cluster
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: external-secrets-secret-reader
  namespace: cnpg-cluster
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: external-secrets-secret-reader
  namespace: cnpg-cluster
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: external-secrets-secret-reader
subjects:
  - kind: ServiceAccount
    name: external-secrets
    namespace: cnpg-cluster
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: external-secrets-secret-writer
  namespace: n8n
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: external-secrets-secret-writer
  namespace: n8n
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: external-secrets-secret-writer
subjects:
  - kind: ServiceAccount
    name: external-secrets
    namespace: cnpg-cluster
