apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: argocd-google-oidc
  namespace: argocd
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: gitlab-cluster-store
  target:
    name: argocd-secret
    creationPolicy: Merge
    template:
      type: Opaque
      data:
        dex.google.clientId: "{{ .clientId }}"
        dex.google.clientSecret: "{{ .clientSecret }}"
  data:
    - secretKey: clientId
      remoteRef:
        key: OIDC_GOOGLE_CLIENT_ID
    - secretKey: clientSecret
      remoteRef:
        key: OIDC_GOOGLE_SECRET
