apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: argocd-google-oidc
  namespace: argocd
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: gitlab-cluster-store
  target:
    name: argocd-google-oidc
    template:
      metadata:
        labels:
          app.kubernetes.io/part-of: argocd
  data:
    - secretKey: clientId
      remoteRef:
        key: OIDC_GOOGLE_CLIENT_ID
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
    - secretKey: clientSecret
      remoteRef:
        key: OIDC_GOOGLE_SECRET
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
