apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: argocd-google-oidc
  namespace: argocd
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: gitlab-cluster-store
  target:
    name: argocd-secret
    creationPolicy: Merge
  data:
    - secretKey: dex.google.clientId
      remoteRef:
        key: OIDC_GOOGLE_CLIENT_ID
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
    - secretKey: dex.google.clientSecret
      remoteRef:
        key: OIDC_GOOGLE_SECRET
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
