apiVersion: v2
name: external-secrets
description: A Helm chart for deployment external-secrets on Kubernetes
type: application
version: 0.20.3
dependencies:
  - name: external-secrets
    version: 0.20.4
    repository: https://charts.external-secrets.io
